version: '3.8'
services:
  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./.env

    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
